#!/bin/bash

VERTX_VERSION="1.3.1.final"

cd $OPENSHIFT_DATA_DIR

# Install Vert.x if needed

if [[ -d vert.x-${VERTX_VERSION} ]]; then
	echo "Vert.x ${VERTX_VERSION} already installed."
else
	for version in vert.x-*; do 
		echo "Removing $version"
		rm -rf $version 
	done

	echo "Installing Vert.x $VERTX_VERSION"

  echo " Downloading http://vertx.io/downloads/vert.x-${VERTX_VERSION}.tar.gz"
	curl --insecure -o vert.x-${VERTX_VERSION}.tar.gz "http://vertx.io/downloads/vert.x-${VERTX_VERSION}.tar.gz"
	tar -xf vert.x-${VERTX_VERSION}.tar.gz
	rm vert.x-${VERTX_VERSION}.tar.gz
fi



