#!/bin/bash

. "${OPENSHIFT_REPO_DIR}.openshift/config.example"

cd $OPENSHIFT_REPO_DIR$EXAMPLE_DIR
pwd

echo "Starting Vert.x application!"

nohup bash -c "exec 'vertx' 'run' '${SERVER_FILE}' &> ${OPENSHIFT_DIY_LOG_DIR}vert.x.log" &> /dev/null &
