#!/bin/bash

. "${OPENSHIFT_REPO_DIR}.openshift/config.example"

echo "{\"host\":\"${OPENSHIFT_DIY_IP}\",\"port\":${OPENSHIFT_DIY_PORT}}" > ${OPENSHIFT_REPO_DIR}.openshift/vertx.config

cd $OPENSHIFT_REPO_DIR$EXAMPLE_DIR

echo "Starting Vert.x application!"

nohup bash -c "exec 'vertx' 'run' '${SERVER_FILE}' -conf ${OPENSHIFT_REPO_DIR}.openshift/vertx.config &> ${OPENSHIFT_DIY_LOG_DIR}vert.x.log" &> /dev/null &
